// /pages/api/followup.js
import { OpenAI } from 'openai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { answer, category } = req.body;

  if (!answer || !category) {
    return res.status(400).json({ error: 'Missing answer or category' });
  }

  try {
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You're a friendly marketing expert helping a contractor take a quiz about their business. For each answer they give, respond in a brief, conversational tone with a helpful comment, encouragement, or a quick insight. Mention the category and lightly affirm or explain their answer. Limit to 1–3 short sentences.`
        },
        {
          role: 'user',
          content: `Category: ${category}\nAnswer: ${answer}`
        }
      ],
      temperature: 0.7
    });

    const followup = completion.choices?.[0]?.message?.content?.trim();

    if (!followup) {
      console.warn("⚠️ No follow-up message generated by GPT");
      return res.status(200).json({ followup: "Thanks for sharing that! Let's keep going." });
    }

    return res.status(200).json({ followup });
  } catch (error) {
    console.error('GPT follow-up error:', error);
    return res.status(500).json({ error: 'Failed to generate follow-up' });
  }
}
